rails-social-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-social-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-social-app/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

rails-social-app/app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: 'User'
	belongs_to :followee, class_name: 'User'
end

rails-social-app/app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
	validates :name, presence: true
end

rails-social-app/app/models/tweet.rb
class Tweet < ApplicationRecord

	mount_uploader :attachment, AttachmentUploader
	has_many :tweet_tags, dependent: :destroy
	has_many :tags, through: :tweet_tags
	validates :body, presence: true
    has_many :likes, dependent: :destroy

	belongs_to :user
end

rails-social-app/app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tag
	belongs_to :tweet
end

rails-social-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followees, through: :active_relationships

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followee_id
  has_many :followers, through: :passive_relationships

  def follow(user)
  	followees << user if !self.following?(user) && self !=user
  end

  def unfollow(user)
  	followees.delete(user)
  end

  def following?(user)
  	followees.include?(user)
  end

  def feed
  	following_ids = "SELECT followee_id FROM relationships WHERE follower_id = :user_id"

  	following_names = "SELECT username FROM users WHERE follower_id = :user_id"

  	Tweet.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end
end

rails-social-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
   	   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
   end	 

end

rails-social-app/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  def create
    if already_liked?
   		 flash[:notice] = "You can't like more than once"
  	else
   		 @tweet.likes.create(user_id: current_user.id)
  	end
  end


  def destroy
  	if !(already_liked?)
   	 flash[:notice] = "Cannot unlike"
    else
   		 @like.destroy
  	end
  end


  private

  def already_liked?
 	 Like.where(user_id: current_user.id, tweet_id:
  	 params[:tweet_id]).exists?
  end

  def find_post
    @tweet = Tweet.find(params[:tweet_id])
  end

  def find_like
     @like = @tweet.likes.find(params[:id])
  end
end

rails-social-app/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		user = User.find(params[:followee_id])
		current_user.follow(user)
		redirect_to users_path
	end

	def destroy
		current_user.unfollow(params[:id])
		redirect_to users_path
	end
end

rails-social-app/app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		    if params[:name]
    		@tags = Tag.where('name LIKE ?', "%#{params[:name]}%")
    
 	   	    else
				@tags = Tag.where("created_at >= ?", Time.zone.now.beginning_of_day)
	   		end
	end

	def show
		@tag = Tag.find(params[:id])
		@tweets = @tag.tweets.all
		@count = @tweets.length
		@user_names = User.pluck(:username)
	end


end

rails-social-app/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :authenticate_user!
	def index
		@tweet = Tweet.new
		@user_names = User.pluck(:username)
		if params[:body]
    		@tweets = current_user.feed.where('body LIKE ?', "%#{params[:body]}%")
    
 	    else
		@tweets = current_user.feed.order("created_at DESC")
	   end
	end

	def create
		@tweet = current_user.tweets.new(tweet_params)
		@array_for_tag = @tweet.body.scan(/#\w+\b/)
		@tweet.body = @tweet.body.gsub(Regexp.union(@array_for_tag), '')
		@tweet.save
	    

	    unless @array_for_tag == []
	    	@array_for_tag.each do |tag|
	    		@tag = Tag.find_or_initialize_by(name: tag)
	    		@tag.save
	    		@tweet.tags << @tag
	        end
	    end


	    redirect_to tweets_path
	    flash[:notice] = "Thanks for posting!"
	end

	def destroy
		Tweet.destroy(params[:id])
		redirect_to tweets_path
	end

	private
		def tweet_params
			params.require(:tweet).permit(:body, :attachment)
		end
end

rails-social-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	
		if params[:username]
    		@users = User.where('username LIKE ?', "%#{params[:username]}%")
    
 	    else
		@users = User.where('username != ?', "#{current_user.username}")
	    end
	end
	def show
		@user_names = User.pluck(:username)
		@user = User.find(params[:id])
	end
end

rails-social-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-social-app/app/helpers/likes_helper.rb
module LikesHelper
end

rails-social-app/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

rails-social-app/app/helpers/tags_helper.rb
module TagsHelper
end

rails-social-app/app/helpers/tweets_helper.rb
module TweetsHelper
end

rails-social-app/app/helpers/users_helper.rb
module UsersHelper
	def hello
		 @array = Array.new
                        @user.follower_ids.each do |f|
                        @array.push(@user.followers.find(f).username)
                        return @array
                    end
	end
end

rails-social-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-social-app/app/views/shared/_nav-bar.html.erb
<table cellpadding="20px">
  <th><a id="nav" class="active"><%= button_to "Tweeter", "/users" ,method: :get %></a></th>
  <th><a id="nav"><%= button_to "Home", root_path , method: :get%></a></th>
  <th><a id="nav"><%= button_to "Trending", "/tags", method: :get %></a></th>
  <th><a id="nav"><%= button_to "Log Out", destroy_user_session_path, :method => :delete %></a></th>
  <th style="float:right;margin-left: 1000px;border: 1px solid black;"><h2 id="nav"><%= link_to current_user.username, user_path(current_user) %></h2></th>
</table>

rails-social-app/app/views/shared/_tweet-table.html.erb
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
	$(function() {
      $('.myLink').bind('ajax:success', function() {
  			 $(this).closest('#likes').fadeIn();
		});
    })
</script> -->
<ul>
	<% @tweets.each do |tweet| %>
	<li>
		<%= tweet.body %>
	</li>
	<% if current_user.id == tweet.user_id %>
	<%= link_to tweet_path(tweet), method: :delete do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/61/61848.svg", class: "delete" %>
    <% end %>
    <% end %>
	<br/>
	
	<% tweet.tags.each do |tag| %>
		<%= link_to "#{tag.name}", tag_path(tag) %>
	<% end %>
    <br/>
 
	

	

	
	
	
	 <% if tweet.attachment_url.to_s.split(".").last == "jpg" || tweet.attachment_url.to_s.split(".").last == "jpeg" || tweet.attachment_url.to_s.split(".").last == "gif" || tweet.attachment_url.to_s.split(".").last == "png" %>
		<img src="<%= tweet.attachment_url %>"> 
	 <% elsif tweet.attachment_url.to_s.split(".").last == "mp4" || tweet.attachment_url.to_s.split(".").last == "avi" || tweet.attachment_url.to_s.split(".").last == "avi" %>
	 	
		<video width="320" height="240" controls autoplay muted>
 				 <source src="<%= tweet.attachment_url %>" type="video/mp4">
		</video>
	<% end %>
	<br/>
	<div id="likes">
    <% if tweet.likes.count > 0 %>
	<p><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%>
        
		<%= select_tag 'user_id', options_for_select(tweet.likes.map {|u| [@user_names[u.user_id.to_i - 1],u.user_id] }) %>
	</p>
	<% end %>
    </div>

	<small><%= tweet.created_at.to_s.slice(0..19).to_s.slice(0..19) %></small>
	<br/>
	<br/>
	<% pre_like = tweet.likes.find { |like| like.user_id == current_user.id} %>
			<% if pre_like %>
 				 <%= button_to 'Unlike', tweet_like_path(tweet, pre_like), method: :delete  %>
			<% else %>
  				<%= button_to 'Like', tweet_likes_path(tweet), method: :post %>
			<% end %>
	<hr>


 
	<% end %>
</ul>

rails-social-app/app/views/tags/index.html.erb
<%= render partial: 'shared/nav-bar' %>
<br/>
<br/>
<h1 class="jumbotron"> Trending </h1>
<br/>
<br/>
<div class="container">
	<div class="card my-2 p-3">
	<%= form_tag(tags_path, method: :get) do %>
 	<%= text_field_tag :name, params[:name], placeholder: "Search!" %>
 	<%= submit_tag 'Search', name: nil %>
	<% end %>
	<br/>
	<br/>
	<ul>
		<% @tags.sort_by { |tage| tage.tweets.count * -1 }.each_with_index do |tag, i| %>
         <% if i==0 %>
         <li class="nav-head">
			<h3><%= i+1 %>.</h3> 
			<% if tag.tweets.count != 0%>
			<h1> <%= link_to "#{tag.name}",tag_path(tag), class: "nav-item" %></h1>
			
			<h3><%= tag.tweets.count %> tweets </h3>
             <% end %>
		</li>
		<br/>
		<br/>
		<br/>
		<br/>
         <% else %>
         <li class="nav-head">
			<p><%= i+1 %>.</p> 
			<% if tag.tweets.count != 0 %>
			<h3> <%= link_to "#{tag.name}",tag_path(tag), class: "nav-item" %></h3>
			
			<p><%= tag.tweets.count %> tweets </p>
             <% end %>
		</li>
         <% end %>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<hr>
		<% end %>
	</ul>

	</div>
<div>

rails-social-app/app/views/tags/show.html.erb
<h1 class="jumbotron"> Tweets with <%= @tag.name %> </h1>
<% if @count > 1 %>
<h3 class="jumbotron"> <%= @count %> tweets </h3>
<% elsif @count == 1  %>
<h3 class="jumbotron"> Single Tweet </h3>
<% else %>
<h3 class="jumbotron"> No Tweets found for this tag </h3>
<% end %>
<div class="container">
	<%= render "shared/tweet-table" %>
</div>

rails-social-app/app/views/users/index.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= render partial: 'shared/nav-bar' %>
<br/>
<br/>
<h1 class="jumbotron"> Welcome to Twitter </h1>
<br/>
<br/>
<div class="container">
	<div class="card my-2 p-3">
	<%= form_tag(users_path, method: :get) do %>
 	<%= text_field_tag :username, params[:username], placeholder: "Search!" %>
 	<%= submit_tag 'Search', name: nil %>
	<% end %>
	<br/>
	<br/>
	<ul class="users-head">
		<% @users.each do |user| %>
		<% unless user == current_user %>
		<li class="users-item">
			<%= link_to "#{user.username}",user_path(user), class: "users" %>
		</li>
		<% end %>
		<br/>
		<br/>		
		<% unless current_user == user %>
		<% unless current_user.following?(user) %>
		<%= form_for(current_user.active_relationships.build) do |f| %>
		<div>
			<%= hidden_field_tag :followee_id, user.id %>
		</div>
		<%= f.submit "Follow", class: "btn btn-primary my-button" %>
		<% end %>
		<% end %>
		<%= link_to 'Unfollow', relationship_path(user), method: :delete, class: "btn btn-danger" if current_user.following?(@user) %>
		<% end %>
		<br/>
		<br/>
		<hr>
		<% end %>
	</ul>
	
	</div>
<div>

rails-social-app/app/views/users/show.html.erb
<%= render partial: 'shared/nav-bar' %>
<h1 class="jumbotron"> <%= @user.username %> Profile </h1>
<h4>Followers : <%= @user.follower_ids.count %>   
<%= select_tag 'user_id', options_for_select(@user.followers.map {|u| [u.username,u.id] }) %> </h4>

<h4>Following : <%= @user.followee_ids.count %>    
	<%= select_tag 'user_id', options_for_select(@user.followees.map {|u| [u.username,u.id] }, :selected => "1" ) %> </h4>
<br/>
<br/>
<% unless current_user == @user %>
		<% unless current_user.following?(@user) %>
		<%= form_for(current_user.active_relationships.build) do |f| %>
		<div>
			<%= hidden_field_tag :followee_id, @user.id %>
		</div>
		<%= f.submit "Follow", class: "btn btn-primary my-button" %>
		<% end %>
		<% end %>
		<%= button_to 'Unfollow', relationship_path(@user), method: :delete, class: "btn btn-danger" if current_user.following?(@user) %>
		<% end %>
		<br/>
		<br/>
<div class="container">
	<ul>

	<% @user.tweets.each do |tweet| %>
	<li>
		@<%= tweet.user.username %>
		<%= tweet.body %>
		
	</li>
    <% if current_user.id == tweet.user_id %>
	<%= link_to tweet_path(tweet) do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/61/61848.svg", class: "delete" %>
    <% end %>
     <% end %>
	<br/>
	<% tweet.tags.each do |tag| %>
		<%= link_to "#{tag.name}", tag_path(tag) %>
	<% end %>
	<br/>
	<br/>
	<% if tweet.likes.count > 0 %>
	<p><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%>
		<%= select_tag 'user_id', options_for_select(tweet.likes.map {|u| [@user_names[u.id.to_i - 1],u.id] }) %>
	</p>
	<% end %>
	<small><%= tweet.created_at.to_s.slice(0..19).to_s.slice(0..19) %></small>
	<br/>
	<br/>
	<% pre_like = tweet.likes.find { |like| like.user_id == current_user.id} %>
			<% if pre_like %>
 				 <%= button_to 'Unlike', tweet_like_path(tweet, pre_like), method: :delete %>
			<% else %>
  				<%= button_to 'Like', tweet_likes_path(tweet), method: :post %>
			<% end %>
	<hr>

	<% end %>
</ul>
	</div>
<div>