rails-app-flyway/config/routes.rb
Rails.application.routes.draw do

  # get 'resumes/index'

  # get 'resumes/new'

  # get 'resumes/create'

  # get 'resumes/destroy'

  devise_for :users
  get 'home/index'
  resources :comments
  resources :posts do #nested routes for individual resumes/ files
  	resources :resumes	
  end
  root :to => "home#index"

  # resources :resumes, only: [:index, :new, :create, :destroy]
  
end

rails-app-flyway/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-app-flyway/app/models/post.rb
class Post < ApplicationRecord
	has_many :resumes
end

rails-app-flyway/app/models/resume.rb
class Resume < ActiveRecord::Base
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
   belongs_to :post
end

rails-app-flyway/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails-app-flyway/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
 	 	stored_location_for(resource) || posts_path
	end
end

rails-app-flyway/app/controllers/concerns/accessible.rb
module Accessible
 
end

rails-app-flyway/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@resumes = Resume.all
  end
end

rails-app-flyway/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	def index
		@post = Post.all
    @post = Post.includes(:resumes)
	end

	def new
		@post = Post.new
	end

	def create
	  @post = Post.new(post_params)
	  @post.save
    redirect_to posts_path
  end  

  def show

  end   

  def edit
  	
  end

  def update
   	@post.update(post_params)
   	redirect_to posts_path
  end

  def destroy
   	@post.destroy
   	redirect_to posts_path
  end

  def set_post
  	@post = Post.find(params[:id])
  end
  def post_params
  	params.require(:post).permit(:title, :body)
  end
end

rails-app-flyway/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :check_post, only: [:new, :create]

  def index
    @resumes = Resume.all
  end

  def new
    @resume = @post.resumes.new
  end

  def create
    @resume = @post.resumes.new(resume_params)	
    if @resume.save
      redirect_to posts_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to post_resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

  private

  def check_post
    @post = Post.find(params[:post_id])
  end

  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end
end

rails-app-flyway/app/controllers/upload_controller.rb
class UploadController < ApplicationController

def index
  @uploads = Upload.all
end

def new
  @uploads = Upload.new
end

def create
  @uploads = Upload.new(upload_params)
  if @uploads.save
    redirect_to uploads_path, notice: "The upload #{@uploads.name} has been uploaded"
  else
    render "new"
  end
end

def destroy
  @uploads = Upload.find(params[:id])
  @uploads.destroy
  redirect_to uploads_path, notice: "The upload #{@uploads.name} has been deleted."
end

private

def upload_params
  params.require(:uploads).permit(:name, :attachment)
end
end

rails-app-flyway/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-app-flyway/app/helpers/comments_helper.rb
module CommentsHelper
end

rails-app-flyway/app/helpers/home_helper.rb
module HomeHelper
end

rails-app-flyway/app/helpers/posts_helper.rb
module PostsHelper
end

rails-app-flyway/app/helpers/resumes_helper.rb
module ResumesHelper
end

rails-app-flyway/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-app-flyway/app/views/posts/_form.html.erb
<%= form_for(@post) do |form| %>

	<%= form.label :Name %>
	<%= form.text_field :title, id: :post_title %>

	<%= form.label :Description %>
	<%= form.text_area :body, id: :post_body %>

	<%= form.submit %>
<% end %>

rails-app-flyway/app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form' %>

<%= link_to 'Show', @post, class: "btn btn-primary" %> |
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

rails-app-flyway/app/views/posts/index.html.erb
<%= link_to('Logout', destroy_user_session_path, method: :delete,class: "btn btn-primary") %>
<%= link_to 'New Post', new_post_path,class: "btn btn-primary" %>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
      
   
        <td><%= link_to 'Show', post , class: "btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
        <td><%= link_to "New Resume", new_post_resume_path(post), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

rails-app-flyway/app/views/posts/new.html.erb
<h1>Create New Post</h1>
<%= render 'form' %>

<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

rails-app-flyway/app/views/posts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.body %>
</p>

<table class = "table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
    </tr>
  </thead>

  <tbody>
    <% @post.resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= link_to "Download Resume", resume.attachment_url %></td>
        <td><%= button_to "Delete",post_resume_path(@post, resume),  method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
      </tr> 
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %> |
<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

rails-app-flyway/app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

rails-app-flyway/app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

rails-app-flyway/app/views/resumes/index.html.erb
<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         
         <tr>
            <td><%= resume.name %></td>
            <td><%= link_to "Download Resume", resume.attachment_url %></td>
            <td><%= button_to "Delete",  post_resume_path(resume.post.id, resume.id), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

rails-app-flyway/app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for [:post, @resume], html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>